INSERT INTO `games` (`gameuuid`, `title`, `description`) VALUES
(UUID(), 'Uno', 'Uno is a classic card game where players try to be the first to get rid of all their cards.'),
(UUID(), 'Poker', 'Poker is a popular card game involving betting and strategy.'),
(UUID(), 'Solitaire', 'Solitaire is a single-player card game played with a standard deck of cards.'),
(UUID(), 'Bridge', 'Bridge is a trick-taking card game using a standard deck of 52 cards.'),
(UUID(), 'Hearts', 'Hearts is a trick-taking game where the goal is to avoid certain cards that carry penalty points.'),
(UUID(), 'Rummy', 'Rummy is a group of matching-card games notable for similar gameplay based on matching cards of the same rank or sequence and same suit.'),
(UUID(), 'Spades', 'Spades is a trick-taking game, similar to hearts, where players try to win as many tricks as possible.'),
(UUID(), 'Cribbage', 'Cribbage is a card game traditionally for two players, but commonly played with three, four or more, that involves playing and grouping cards in combinations.'),
(UUID(), 'Euchre', 'Euchre is a trick-taking card game most commonly played with four people in two partnerships with a deck of 24, 28, or sometimes 32, standard playing cards.'),
(UUID(), 'Gin Rummy', 'Gin Rummy is a two-player card game created in 1909 by Elwood T. Baker and his son C. Graham Baker.'),
(UUID(), 'Crazy Eights', 'Crazy Eights is a shedding-type card game for two to seven players.'),
(UUID(), 'Canasta', 'Canasta is a card game of the rummy family of games believed to be a variant of 500 Rum.'),
(UUID(), 'War', 'War is a simple card game, typically played by two players using a standard playing card deck; the objective is to win all of the cards.'),
(UUID(), 'Go Fish', 'Go Fish is a simple card game played by children to teach concepts such as matching, pairing, and collecting.'),
(UUID(), 'Old Maid', 'Old Maid is a Victorian card game for two or more players probably deriving from an ancient gambling game in which the loser pays for the drinks.'),
(UUID(), 'Snap', 'Snap is a matching game, often played with custom decks specifically designed for the game.'),
(UUID(), 'Blackjack', 'Blackjack, also known as 21, is a comparing card game between one or more players and a dealer, where each player in turn competes against the dealer.'),
(UUID(), 'Pinochle', 'Pinochle is a trick-taking and melding card game with European roots.'),
(UUID(), 'Tong-its', 'Tong-its is a popular Filipino rummy-style card game originating in the northern Philippines.'),
(UUID(), 'Spite and Malice', 'Spite and Malice is a card game for two or more players also known as Cat and Mouse or Screw Your Neighbor.');
